[project]
name = "xrp-ws-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hamidh-2k8", email = "hamidh.2k8@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
    "websockets>=17.0.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.extra-build-dependencies]
pygame = ["setuptools._distutils.msvccompiler"]
